apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
